version: '3.8'
services:
  forecast:
    build: ./prediction
    container_name: forecast-runner
    env_file:
      - ./server/.env
    command: python forecast.py
    volumes:
      - ./prediction:/app
  anomaly_cleaner:
    build: ./anomaly
    container_name: anomaly-cleaner-runner
    env_file:
      - ./server/.env
    command: python anomaly_cleaner.py
    volumes:
      - ./anomaly:/app
