name: Deploy to AWS Pipeline

on:
  push:
    branches:
      - deploy  # Trigger on pushes to the deploy branch

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    # Step 3: Set up SSH for deployment
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Step 4: Deploy code and run tasks on the server
    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
        set -e
        cd /var/www/mrrm
        echo "Pulling latest changes from the repository..."
        git pull origin deploy

        echo "Installing dependencies..."
        npm ci --prefix frontend
        npm ci --prefix server

        echo "Building the frontend..."
        npm run build:frontend

        echo "Deploying and restarting services..."
        npm run deploy
        sudo systemctl restart nginx
        echo "Deployment completed successfully!"
        EOF
